### ISSUE TITLE
Tracking issue: Add missing articles

### ISSUE THREAD

**Issue by anonymous123-code** [QuiltMC/developer-wiki#69]
Currently there are quite a few article stubs, which should be replaced  with complete articles.
Currently missing articles are:
- [ ] Items
  - [ ] Tools
- [ ] #4
  - [ ] Oriented Block #111 
  - [ ] Redstone Interaction
- [ ] Concepts
  - [ ] Events
  - [ ] List of Third Party Libraries
  - [ ] Lifecycles and Ticks
  - [ ] Minecraft’s Code Structure
  - [ ] #6
  - [ ] Nbt
  - [ ] Networking
  - [ ] Registires
  - [ ] Sideness
- [ ] Data
  - [ ] Adding Recipes (Has a small [old wiki article](https://github.com/QuiltMC/developer-wiki/blob/old/wiki/versions/1.19/data/recipes/markdown/recipes.md), needs major rework)
  - [ ] REA
  - [ ] Recipe API (Has an [old wiki article](https://github.com/QuiltMC/developer-wiki/blob/old/wiki/versions/1.19/data/recipes/markdown/recipe_api.md), might need some updating)
  - [ ] Recipe Type (Has an [old wiki article](https://github.com/QuiltMC/developer-wiki/blob/old/wiki/versions/1.19/data/recipes/markdown/recipe_type.md), might need some updating)
  - [ ] #83 
- [x] configuration
  - [x] basic configuration (https://github.com/QuiltMC/developer-wiki/pull/81)
  - [x] more advanced stuff (https://github.com/QuiltMC/developer-wiki/pull/81)
  - [x] metadata reference (https://github.com/QuiltMC/developer-wiki/pull/81)
  - [ ] config screens  
- [ ] Misc
  - [ ] Sounds
  - [ ] Commands

**Comment by woodiertexas** [comment]
Aren't the TODOs found here also listed in the checklist of stuff to do? https://modder.wiki.quiltmc.org/introduction/get-started

**Comment by OroArmor** [comment]
> Aren't the TODOs found here also listed in the checklist of stuff to do? https://modder.wiki.quiltmc.org/introduction/get-started

Those should probably be moved to issues instead of being left on the pages

**Comment by Redfan2** [comment]
What do you think about adding a Article about Block Entites to the list?

**Comment by Redfan2** [comment]
It should probably be a seperate section, like this:

- [ ] Block Entities
  - [ ] Adding a Block Entity
  - [ ] Adding a Block Entity Renderer
  - [ ] Adding a inventory to a block entity
  
For clarifications, I do not plan on writing these at the moment. I do not have enough knowledge about block entities and currently not the time to dive into this topic.

**Comment by woodiertexas** [comment]
There's a PR for orientable blocks here: https://github.com/QuiltMC/developer-wiki/pull/111

**Comment by woodiertexas** [comment]
A couple of issues that could be added here:
https://github.com/QuiltMC/developer-wiki/issues/113
https://github.com/QuiltMC/developer-wiki/issues/102
https://github.com/QuiltMC/developer-wiki/issues/107
https://github.com/QuiltMC/developer-wiki/issues/97
https://github.com/QuiltMC/developer-wiki/issues/71
https://github.com/QuiltMC/developer-wiki/issues/35

**Comment by woodiertexas** [comment]
there's https://github.com/QuiltMC/developer-wiki/issues/114
